In [62]:
# Import Library

In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
# Open the Data set

In [65]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [66]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [67]:
# Remove the categorical data(i.e str-state)

In [68]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [92]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [93]:
# splite the input & output columns

In [94]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [95]:
independant=dataset[['Age', 'EstimatedSalary',  'Gender_Male']]

In [96]:
independant

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [97]:
independant.shape

(400, 3)

In [98]:
dependant= dataset[["Purchased"]]

In [111]:
dependant

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [112]:
#split the Train & Test dataset

In [113]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independant,dependant,test_size=1/3,random_state=0)

In [114]:
X_train

     Age  EstimatedSalary  Gender_Male
218   46            96000            0
101   28            59000            1
311   39            96000            1
194   28            89000            1
326   41            72000            1
..   ...              ...          ...
323   48            30000            0
192   29            43000            1
117   36            52000            1
47    27            54000            0
172   26           118000            0

[266 rows x 3 columns]

In [115]:
# Train data-Model creation

In [116]:
from sklearn.tree import DecisionTreeClassifier
classifier =DecisionTreeClassifier(criterion='entropy',splitter='best',random_state= 0)
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [117]:
# Evaluation Method Presidcting the Test set result

In [118]:

Y_pred= classifier.predict(X_test)

In [119]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)

In [120]:
from sklearn.metrics import classification_report
clf_report =classification_report(Y_test,Y_pred)

In [121]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      0.89      0.90        85
           1       0.82      0.84      0.83        49

    accuracy                           0.87       134
   macro avg       0.86      0.87      0.86       134
weighted avg       0.87      0.87      0.87       134

In [122]:
print( cm)

[[76  9]
 [ 8 41]]

In [124]:
classifier.predict([[40,300,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)